<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="63.107" tests="3" failures="1">
  <testsuite name="Root Suite" timestamp="2025-06-17T09:22:34" tests="0" file="cypress\e2e\tests\LoginTest.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Success and Fail login flow" timestamp="2025-06-17T09:22:34" tests="3" time="63.091" failures="1">
    <testcase name="Success and Fail login flow should login successfully with valid credentials" time="11.033" classname="should login successfully with valid credentials">
    </testcase>
    <testcase name="Success and Fail login flow should fail to login with invalid credentials" time="18.018" classname="should fail to login with invalid credentials">
      <failure message="Timed out retrying after 5000ms: expected &apos;https://goodbudget.com/login&apos; to include &apos;/home&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 5000ms: expected 'https://goodbudget.com/login' to include '/home'
    at LoginPage.loginWithUI (webpack://cypress-framework/./cypress/e2e/pages/LoginPage.js:31:17)
    at Context.eval (webpack://cypress-framework/./cypress/e2e/tests/LoginTest.cy.js:37:13)]]></failure>
    </testcase>
    <testcase name="Success and Fail login flow should perform login and logout" time="15.345" classname="should perform login and logout">
    </testcase>
  </testsuite>
</testsuites>